---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: skillproficiencyclient
  labels:
    app: skillproficiencyclient
spec:
  replicas: 3
  selector:
    matchLabels:
      app: skillproficiencyclient
  template:
    metadata:
      labels:
        app: skillproficiencyclient
    spec:
      containers:
      - name: skillproficiencyclient
        image: anandkesam/skillproficiencyclient:xyz
        ports:
        - containerPort: 8080

  
